# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
